name: language-learning-app-dev

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    restart: unless-stopped

    env_file: ./frontend/.env

    networks:
      - language-learning-app

    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
            - dist

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

    restart: unless-stopped

    env_file: ./backend/.env

    networks:
      - language-learning-app

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules
            - dist
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - language-learning-app

    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  language-learning-app:
    driver: bridge
