GET http://localhost:3000/api/v1/dictionary
###
GET http://localhost:3000/api/v1/dictionary/search?q=す
####
GET http://localhost:3000/api/v1/immersion/videos/C3oPjuudXas/subtitles
####
GET http://localhost:3000/api/v1/immersion/topics
####
POST http://localhost:3000/api/v1/immersion/topics
Content-Type: application/json

{
  "name": "Genshin",
  "coverImg": "",
  "type": "custom"
}
####
DELETE http://localhost:3000/api/v1/immersion/topics/6a2df8d66128b1c9d0f6aae0
####
GET http://localhost:3000/api/v1/immersion/topics/6a2dd8285692d341fb464062/videos
####
